name: python-app

on: [push, pull_request]

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
# Checkout to the repository on the build machine
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'

    - run: pip install -r requirements.txt

    - name: Docker Build and run
      run:
        docker build . --file Dockerfile --tag python-app
        docker run -dit -p 80:80 python-app

    - name: Test Code
      run: coverage run -m pytest test/

    - name: Generate the report
      if: ${{ always() }}
      run: coverage report > coverage-report

    - name: Scan image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "ntzes/python-app"

    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
        
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-report
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

# build the container image and push it to Docker Hub with the name py
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ntzes/python-app:latest
  
    - name: Create issue on failure
      if: ${{ failure() }}
      run: 
        gh issue create --title "Failure on workflow:${{github.workflow}} - ${{github.sha}}" --body "Failure on Job:${{ github.job}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
