name: python-app

on: [push, pull_request]

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
# Checkout to the repository on the build machine
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
        cache: 'pip'
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - run: pip install -r requirements.txt

    - name: Docker Build and run
      run:
        docker build . --file Dockerfile --tag python-app

    - name: Install dependencies
      run:
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    
    - name: Test Code
      run: 
        pip install pytest pytest-cov

    - name: Test with pytest  
      run:  
        coverage run -m pytest  -v -s
      continue-on-error: true
      
    - name: Generate Coverage Report  
      run:
        coverage report -m
      continue-on-error: true
        
    - uses: actions/upload-artifact@v4
      with:
        name: test-results.xml
        path: ./
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

# build the container image and push it to Docker Hub with the name py
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ntzes/python-app:latest
  
    - name: Create issue on failure
      if: ${{ failure() }}
      run: 
        gh issue create --title "Failure on workflow:${{github.workflow}} - ${{github.sha}}" --body "Failure on Job:${{ github.job}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
